#!/usr/bin/env python3
"""Check the invariants the 足下 code layout is supposed to guarantee.

This is the machine half of an audit: it does not judge design, it only
asserts that the shipped files actually are what the design says they are.
Everything here is derived from `data/zuxia.dict.yaml` itself, so it also
catches a dictionary that was edited by hand or generated by a stale script.

    python data-tools/audit_zuxia.py            # check the committed files
    python data-tools/audit_zuxia.py --regen    # also rebuild and diff bytes

`--regen` is the expensive one and the one that matters most: it reruns the
generator into a temporary directory and compares byte for byte, which proves
both that the output is deterministic and that what is committed is what the
current source produces.
"""
from __future__ import annotations

import argparse
import filecmp
import pathlib
import re
import unicodedata
import shutil
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent


def strip_tone(text: str) -> str:
    text = text.lower().replace("ü", "v").replace("u:", "v")
    decomposed = unicodedata.normalize("NFD", text)
    return "".join(c for c in decomposed if not unicodedata.combining(c))


FAILURES: list[str] = []


def check(label: str, ok: bool, detail: str = "") -> None:
    print(f"  {'PASS' if ok else 'FAIL'}  {label}")
    if detail and not ok:
        print(f"        {detail}")
    if not ok:
        FAILURES.append(label)


def read_dict(path: pathlib.Path) -> tuple[list[tuple[str, str, str]], list[str]]:
    """Return (char, code, weight) rows plus the raw body lines."""
    rows, body, started = [], [], False
    for line in path.read_text(encoding="utf-8").splitlines():
        if not started:
            started = line.startswith("...")
            continue
        body.append(line)
        parts = line.split("\t")
        if len(parts) >= 2:
            rows.append((parts[0], parts[1], parts[2] if len(parts) > 2 else ""))
    return rows, body


def load_readings(path: pathlib.Path) -> dict[str, set[str]]:
    """The readings the generator was fed, straight from the charset source.

    Checking the dictionary against its own generator would be circular, so
    the ladder is verified against the input instead: every reading in the
    charset must appear as a bare code, and every code must hang off one.
    """
    out: dict[str, set[str]] = {}
    started = False
    for line in path.read_text(encoding="utf-8").splitlines():
        if not started:
            started = line.startswith("...")
            continue
        if line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) >= 2 and parts[0] and parts[1]:
            reading = strip_tone(parts[1])
            if reading.isascii() and reading.isalpha():
                out.setdefault(parts[0], set()).add(reading)
    return out


def ladder(codes: set[str], readings: set[str]) -> dict[str, set[str]]:
    """Split a character's codes into {reading: {suffixes}}.

    Longest reading wins, so 洗's `xianz` lands under xian rather than under
    xi with a nonsense tail.
    """
    roots = sorted(readings, key=len, reverse=True)
    out: dict[str, set[str]] = {r: set() for r in roots}
    for code in codes:
        for root in roots:
            if code.startswith(root):
                out[root].add(code[len(root):])
                break
    return out


def audit_dictionary(path: pathlib.Path, structured: bool) -> None:
    rows, body = read_dict(path)
    readings = load_readings(ROOT / "data-tools/sources/8105.dict.yaml")
    print(f"\n词典不变量 — {path.relative_to(ROOT)}  ({len(rows)} 行)")

    bad = [c for _, c, _ in rows if not re.fullmatch(r"[a-z]+", c)]
    check("每个码都只含 a–z", not bad, f"{len(bad)} 个越界码，例如 {bad[:5]}")
    junk = sorted({ch for ch, _, _ in rows if len(ch) != 1})
    check("每个候选就是一个汉字（没有注释符、没有整行漏进来）", not junk,
          f"{len(junk)} 个，例如 {junk[:5]}")

    check("没有重复行", len(set(body)) == len(body),
          f"{len(body) - len(set(body))} 行重复")
    pairs = [(ch, co) for ch, co, _ in rows]
    check("没有重复的（字，码）对", len(set(pairs)) == len(pairs),
          f"{len(pairs) - len(set(pairs))} 对重复")

    by_char: dict[str, set[str]] = {}
    for ch, co, _ in rows:
        by_char.setdefault(ch, set()).add(co)

    stem_bad, pair_bad, single_bad, long_bad, struct_bad = [], [], [], [], []
    orphan, stems_seen = [], 0
    for ch, codes in by_char.items():
        letters: set[str] = set()
        heard = readings.get(ch, set())
        if not heard:
            orphan.append(ch)
            continue
        for root, tails in ladder(codes, heard).items():
            if not tails:
                stem_bad.append((ch, root, "读音没出码"))
                continue
            if "" not in tails:
                stem_bad.append((ch, root, "缺光秃全拼"))
            depth = 1 if structured else 0
            if structured and len({t[:1] for t in tails if t}) > 1:
                stem_bad.append((ch, root, "一个读音下出现多个结构码"))
            stems_seen += 1
            suffixes = {t[depth:] for t in tails if len(t) >= depth}
            if any(len(s) > 2 for s in suffixes):
                long_bad.append((ch, root))
            for s in suffixes:
                if len(s) == 2:
                    if s[::-1] not in suffixes:
                        pair_bad.append((ch, root, s))
                    if s[0] not in suffixes or s[1] not in suffixes:
                        single_bad.append((ch, root, s))
            if structured:
                letters |= {t[:1] for t in tails if t}
        if structured and len(letters) > 1:
            struct_bad.append((ch, sorted(letters)))

    check("字表里的每个读音都长出完整的一梯码", not stem_bad,
          f"{len(stem_bad)} 处，例如 {stem_bad[:5]}")
    check("词典里没有字表之外的字", not orphan,
          f"{len(orphan)} 个，例如 {orphan[:5]}")
    check("满码不超过「词干＋两位」", not long_bad, f"例如 {long_bad[:5]}")
    check("两部件码的两种顺序都在", not pair_bad, f"例如 {pair_bad[:5]}")
    check("每个两部件码的单部件中间级都在", not single_bad, f"例如 {single_bad[:5]}")
    if structured:
        check("同一个字的所有读音共用同一个结构码", not struct_bad,
              f"例如 {struct_bad[:5]}")
    print(f"        （{len(by_char)} 字，{stems_seen} 个读音，"
          f"{len({c for _, c, _ in rows})} 个不同的码）")
    return by_char


def audit_char_codes(by_char: dict[str, set[str]], path: pathlib.Path) -> None:
    rows, _ = read_dict(path)
    print(f"\n候选注释表 — {path.relative_to(ROOT)}  ({len(rows)} 行)")
    missing, not_maximal = [], []
    for ch, code, _ in rows:
        codes = by_char.get(ch)
        if codes is None or code not in codes:
            missing.append((ch, code))
        elif any(o != code and o.startswith(code) for o in codes):
            not_maximal.append((ch, code))
    check("注释表里的每个码都在主词典里", not missing, f"例如 {missing[:5]}")
    check("注释表只收满码（没有别的码以它为前缀）", not not_maximal,
          f"例如 {not_maximal[:5]}")


def audit_legacy(by_char: dict[str, set[str]]) -> None:
    """应物 users type pinyin+structure; those must stay valid rungs."""
    print("\n与应物码位的兼容")
    samples = [("清", "qingzs"), ("情", "qingzx"), ("应", "yingbg"),
               ("字", "zisb"), ("行", "hangzc")]
    bad = [(ch, code) for ch, code in samples if code not in by_char.get(ch, ())]
    check("应物风格的「全拼＋结构＋部首首字母」仍是有效中间码", not bad,
          f"缺失 {bad}")


def audit_versions() -> None:
    print("\n版本号一致性")
    want = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    # setup.rc 里那一行手写的窗口标题和 RELEASE-NOTES.md 里的安装包文件名
    # 原先都不在清单里 —— 外部复审就是靠 setup.rc:14 发现版本号漏改的。
    spots = {
        "CMakeLists.txt": r"project\([^)]*VERSION\s+([0-9.]+)",
        "data/zuxia.schema.yaml": r"version:\s*[\"']?([0-9.]+)",
        "installer/setup/zxcommon.h": r"ZX_VERSION\s+L?\"([^\"]+)\"",
        "installer/setup/setup.rc": r"足下输入法 ([0-9][0-9.]*)",
        "installer/RELEASE-NOTES.md": r"ZuxiaSetup-([0-9][0-9.]*)\.exe",
        "src/RimeEngine.cpp": r"distribution_version\s*=\s*\"([^\"]+)\"",
    }
    # 判据原先是 startswith：VERSION 写 0.2 时 0.27 也算过，改成 0.27 时
    # 0.2.0 仍然算过 —— 等于没查。必须严格相等。
    numeric = want.split("-")[0]
    for rel, pattern in spots.items():
        text = (ROOT / rel).read_text(encoding="utf-8")
        found = re.search(pattern, text)
        got = found.group(1) if found else "(未找到)"
        check(f"{rel} = {numeric}", got == numeric, f"实际 {got}")
    # Third-party trees and the rime-ice sources carry version strings of
    # their own; only our own build inputs have to agree.
    owned = ["CMakeLists.txt", "VERSION", "src", "installer", "data/default.yaml",
             "data/zuxia.schema.yaml", "tools/port_from_yingwu.py"]
    # -F 是按字面找。不加它 git grep 会把 0.1.0 当正则，`.` 通配任意字符 ——
    # src/Decoder.cpp 里的 0x10000 就会被当成「残留的旧版本号」误报。
    stale = subprocess.run(["git", "grep", "-l", "-F", "0.1.0", "--", *owned],
                           cwd=ROOT, capture_output=True, text=True).stdout.split()
    check("自有源码里没有残留的旧版本号", not stale, f"{stale}")


def audit_port_script() -> None:
    print("\n移植脚本与源码的一致性")
    port = (ROOT / "tools/port_from_yingwu.py").read_text(encoding="utf-8")
    src = (ROOT / "src/RimeEngine.cpp").read_text(encoding="utf-8")
    block = re.search(r'ANNOTATE_NEW = """(.*?)"""', port, re.S)
    ok = False
    if block:
        want = block.group(1).replace("\\\\u2026", "\\u2026")
        ok = want.strip() in src
    check("port_from_yingwu.py 的 ANNOTATE_NEW 与 src/RimeEngine.cpp 逐字节一致",
          ok, "重跑移植脚本会把 src 的改动打回去")
    kmax = re.findall(r"kMaxCodes = (\d+)", src) + \
        re.findall(r"kMaxCodes = (\d+)", port)
    check("两处的 kMaxCodes 相同", len(set(kmax)) == 1, f"{kmax}")

    # 解码器补位要正好填满候选窗剩下的位置，页大小两边写死一次就得对一次。
    page = re.search(r"page_size:\s*(\d+)",
                     (ROOT / "data/zuxia.schema.yaml").read_text(encoding="utf-8"))
    code = re.search(r"kPageSize = (\d+)", src)
    check("kPageSize 与 schema 的 page_size 相同",
          bool(page and code) and page.group(1) == code.group(1),
          f"schema={page and page.group(1)} src={code and code.group(1)}")


def audit_installer() -> None:
    print("\n安装载荷清单")
    # 会随安装包发出去的数据文件：yaml 之外还有生成器产出的解码器 tsv
    # （CMake 的 install 规则同样按 *.yaml + *.tsv 收录）。
    data = {p.name for p in (ROOT / "data").glob("*.yaml")} | {
        p.name for p in (ROOT / "data").glob("*.tsv")}
    for rel, pattern in [("installer/setup/setup.cpp", r'L"\\\\data\\\\([\w.]+)"'),
                         ("installer/Install-Zuxia.ps1", r"'data\\([\w.]+)'")]:
        text = (ROOT / rel).read_text(encoding="utf-8")
        required = set(re.findall(pattern, text))
        missing = required - data
        check(f"{rel} 要求的文件都存在（{len(required)} 个）", not missing,
              f"缺 {missing}")


def audit_regen() -> None:
    print("\n可复现性（重跑生成器并逐字节比对）")
    outs = []
    for i in range(2):
        tmp = pathlib.Path(tempfile.mkdtemp(prefix=f"zuxia-regen{i}-"))
        subprocess.run([sys.executable, "data-tools/generate_zuxia.py",
                        "--out-dir", str(tmp)], cwd=ROOT, check=True,
                       capture_output=True)
        outs.append(tmp)
    names = ["zuxia.dict.yaml"]
    check("两次生成的结果完全一致",
          all(filecmp.cmp(outs[0] / n, outs[1] / n, shallow=False)
              for n in names))
    check("仓库里的 data/zuxia.dict.yaml 就是当前源码的产物",
          filecmp.cmp(outs[0] / "zuxia.dict.yaml",
                      ROOT / "data/zuxia.dict.yaml", shallow=False))
    tmp = pathlib.Path(tempfile.mkdtemp(prefix="zuxia-nostruct-"))
    done = subprocess.run([sys.executable, "data-tools/generate_zuxia.py",
                           "--no-structure", "--out-dir", str(tmp)],
                          cwd=ROOT, capture_output=True, text=True)
    check("--no-structure 对照构建仍可用", done.returncode == 0,
          done.stderr[-300:])
    if done.returncode == 0:
        plain, _ = read_dict(tmp / "zuxia.dict.yaml")
        main, _ = read_dict(ROOT / "data/zuxia.dict.yaml")
        # 判据要相对，不能钉死行数。别名表一长，两边都会变大；不变的是
        # 「去掉结构码之后，码更短、行更少」。钉死阈值的话，加别名就会把
        # 这条断言撞红，而它其实什么问题都没有。
        plain_max = max(len(r[1]) for r in plain)
        main_max = max(len(r[1]) for r in main)
        check("对照构建确实没有结构码（行更少、码更短）",
              len(plain) < len(main) and plain_max < main_max,
              f"对照 {len(plain)} 行/最长 {plain_max} 键，"
              f"正式 {len(main)} 行/最长 {main_max} 键")
    for path in outs + [tmp]:
        shutil.rmtree(path, ignore_errors=True)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--regen", action="store_true",
                    help="rerun the generator twice and diff the bytes")
    ap.add_argument("--no-structure", dest="structured", action="store_false",
                    help="audit a dictionary built without the structure key")
    args = ap.parse_args()

    by_char = audit_dictionary(ROOT / "data/zuxia.dict.yaml", args.structured)
    audit_char_codes(by_char, ROOT / "data/zuxia_char_codes.dict.yaml")
    if args.structured:
        audit_legacy(by_char)
    audit_versions()
    audit_port_script()
    audit_installer()
    if args.regen:
        audit_regen()

    print(f"\n{'FAILED' if FAILURES else 'ALL CHECKS PASSED'}"
          f" ({len(FAILURES)} failure{'' if len(FAILURES) == 1 else 's'})")
    for name in FAILURES:
        print(f"  - {name}")
    return 1 if FAILURES else 0


if __name__ == "__main__":
    raise SystemExit(main())
