# -*- coding: utf-8 -*-
"""生成足下的完整码表 data/zuxia.extended.dict.yaml（单字表 + 词组）。

词组码与单字码同构，只是按「列」而不是按「字」排：

    全拼串  +  逐位结构串  +  逐位部件串
    suyao      sz            cw          ->  苏瑶

三档都出，打到哪一档算哪一档：

    suyao        全拼
    suyaosz      全拼 + 结构串
    suyaoszcw    全拼 + 结构串 + 部件串

部件位与单字有一处不同：**只取每个字的第一个部件**（左边的 / 上面的 /
外面的那个），它的任何叫法都认。单字那边是任意部件、任意顺序，词组这边
做不到 —— 全展开是 568 万行 150 MB，Rime 的表编译不动。真正的「任意部件」
要靠 docs/列式解码.md 里那个解码器，它不查表，还没移植进 C++。

这张表不进 git（太大），由 CI 在打包前现生成，见 .github/workflows/。它
反过来 import 手里那张 1 MB 的单字表 zuxia.dict.yaml —— 方向这么定是因为
单字表要留在 git 里逐行可审，而它一旦加上 import_tables 就得跟着改。
schema 的 translator/dictionary 指向的是这张 extended 表。
"""
from __future__ import annotations

import argparse
import collections
import json
import math
import pathlib
import sys

# Windows 上 Python 的 stdout 跟着控制台代码页走（GitHub 的 runner 是
# cp1252），一 print 中文就 UnicodeEncodeError —— 连 --help 都会炸，因为
# 这个文件的说明文字是中文的。
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import generate_zuxia as g

HEADER = """# Rime dictionary
# encoding: utf-8
# Generated by data-tools/generate_phrases.py - do not edit by hand.
---
name: zuxia.extended
version: "{version}"
sort: by_weight
import_tables:
  - zuxia
...
"""


def load_words(path: pathlib.Path, limit: int):
    """读 rime-ice base.dict.yaml，按词频取前 limit 条。"""
    rows = []
    body = False
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            if line.startswith("..."):
                body = True
                continue
            if not body or line.startswith("#"):
                continue
            cells = line.rstrip("\n").split("\t")
            if len(cells) < 3 or len(cells[0]) < 2:
                continue
            try:
                weight = int(cells[2])
            except ValueError:
                continue
            rows.append((cells[0], cells[1].split(), weight))
    rows.sort(key=lambda r: -r[2])
    return rows[:limit], rows


def build_char_table(hanzi, ids, names, charset, overrides):
    """字 -> (结构码, 第一个部件的字母们)。"""
    structure: dict[str, str] = {}
    first: dict[str, list[str]] = {}
    for char, pinyin, _weight in charset:
        if char in structure:
            continue  # 多音字只取第一次，结构与部件与读音无关
        source = (hanzi.get(char) or {}).get("decomposition") or ids.get(char, "")
        structure[char] = g.classify_structure(g.parse_ids(source), char, overrides)
        groups = [g.letters_for(p, names, hanzi)
                  for p in g.components_of(char, hanzi, ids)]
        groups = [s for s in groups if s]
        # 拆不出部件的 32 个字（入 心 舟 女 …）用自己拼音的首字母顶上，
        # 与单字码和解码器的补位规则一致。
        first[char] = sorted(groups[0]) if groups else [pinyin[0]]
    return structure, first


def write_decoder_data(path, hanzi, ids, names, charset, overrides, rows,
                       bigram_limit=200000):
    """列式解码器的运行时数据。

    src/Decoder.cpp 读这一个文件就够了。四段，每行第一列是段标：

        s  <音节 音节 …>      合法拼音音节，切词用
        w  <字> <权重>        字频，打分用
        c  <码> <字字字…>     码 -> 字，逐位查表用
        b  <字对> <分数>      相邻二元组，把「杨志鹏」从「样直鹏」里分出来

    c 段不是 data/zuxia.dict.yaml 的副本：那张表缺两条补位规则 ——
    只有一个部件的字没有「第二位重写第一位」，拆不出部件的字没有
    「部件位写拼音首字母」。列式码要求每一位都填得上，这两条必须有。
    """
    weight: dict[str, int] = {}
    syllables: set[str] = set()
    codes: dict[str, set[str]] = collections.defaultdict(set)
    for char, pinyin, w in charset:
        source = (hanzi.get(char) or {}).get("decomposition") or ids.get(char, "")
        st = g.classify_structure(g.parse_ids(source), char, overrides)
        groups = [g.letters_for(p, names, hanzi)
                  for p in g.components_of(char, hanzi, ids)]
        groups = [x for x in groups if x]
        if not groups:
            groups = [{pinyin[0]}]
        weight[char] = max(weight.get(char, 0), w)
        syllables.add(pinyin)
        stem = pinyin + st
        codes[pinyin].add(char)
        codes[stem].add(char)
        for group in groups:
            for letter in group:
                codes[stem + letter].add(char)
        for i, a_set in enumerate(groups):
            for j, b_set in enumerate(groups):
                if i == j:
                    continue
                for a in a_set:
                    for b in b_set:
                        codes[stem + a + b].add(char)
        if len(groups) == 1:
            for a in groups[0]:
                codes[stem + a + a].add(char)

    # 二元组：从词频取对数累加。没有它，纯拼时「杨志鹏」会输给「样直鹏」——
    # 每个字单看都更常见，连起来却没人这么写。
    bigram: dict[str, float] = collections.defaultdict(float)
    for word, _py, freq in rows[:bigram_limit]:
        value = math.log(freq + 1)
        for a, b in zip(word, word[1:]):
            bigram[a + b] += value

    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("# Zuxia columnar decoder data\n")
        handle.write("# Generated by data-tools/generate_phrases.py"
                     " - do not edit by hand.\n")
        handle.write("s\t" + " ".join(sorted(syllables)) + "\n")
        for char in sorted(weight):
            handle.write(f"w\t{char}\t{weight[char]}\n")
        for code in sorted(codes):
            handle.write("c\t" + code + "\t" + "".join(sorted(codes[code])) + "\n")
        for pair in sorted(bigram):
            handle.write(f"b\t{pair}\t{bigram[pair]:.3f}\n")
    return {"syllables": len(syllables), "characters": len(weight),
            "codes": len(codes), "bigrams": len(bigram),
            "bytes": path.stat().st_size}


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--hanzi-data", type=pathlib.Path,
                    default=root / "sources/hanzi-dictionary.txt")
    ap.add_argument("--cjkvi-ids", type=pathlib.Path,
                    default=root / "sources/cjkvi-ids.txt")
    ap.add_argument("--charset", type=pathlib.Path,
                    default=root / "sources/8105.dict.yaml")
    ap.add_argument("--names", type=pathlib.Path,
                    default=root / "sources/component-names.yaml")
    ap.add_argument("--structure-map", type=pathlib.Path,
                    default=root / "sources/structure-overrides.tsv")
    ap.add_argument("--words", type=pathlib.Path,
                    default=root / "sources/base.dict.yaml")
    # 12 万词 ≈ 42 万行 ≈ 12 MB。再往上翻一倍，Rime 第一次部署的等待
    # 就从几秒变成十几秒 —— 那正是 docs/工程排查.md 里记下的那个毛病。
    ap.add_argument("--limit", type=int, default=120000)
    ap.add_argument("--out-dir", type=pathlib.Path, default=root.parent / "data")
    ap.add_argument("--version", default="0.2.0")
    ap.add_argument("--report", type=pathlib.Path)
    args = ap.parse_args()

    hanzi = g.load_hanzi(args.hanzi_data)
    ids = g.load_ids(args.cjkvi_ids)
    names = g.load_names(args.names)
    charset = g.load_charset(args.charset)
    overrides = g.load_structure_overrides(args.structure_map)
    structure, first = build_char_table(hanzi, ids, names, charset, overrides)

    words, all_rows = load_words(args.words, args.limit)
    rows: dict[tuple[str, str], int] = {}
    stats = collections.Counter()
    for word, syllables, weight in words:
        if len(syllables) != len(word):
            stats["syllable count mismatch"] += 1
            continue
        if any(ch not in structure for ch in word):
            stats["character not in the char table"] += 1
            continue
        if not all(s.isalpha() and s.isascii() for s in syllables):
            stats["pinyin is not plain letters"] += 1
            continue
        stats["encoded"] += 1
        sound = "".join(syllables)
        shape = "".join(structure[ch] for ch in word)
        codes = [sound, sound + shape]
        tails = [""]
        for ch in word:
            tails = [t + letter for t in tails for letter in first[ch]]
        codes.extend(sound + shape + t for t in tails)
        for code in codes:
            key = (word, code)
            rows[key] = max(rows.get(key, 0), weight)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    out = args.out_dir / "zuxia.extended.dict.yaml"
    with out.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(HEADER.format(version=args.version))
        for (word, code), weight in sorted(
            rows.items(), key=lambda x: (x[0][1], -x[1], x[0][0])
        ):
            handle.write(f"{word}\t{code}\t{weight}\n")

    decoder = write_decoder_data(args.out_dir / "zuxia.decoder.tsv", hanzi, ids,
                                 names, charset, overrides, all_rows)

    report = {
        "decoder": decoder,
        "words_considered": len(words),
        "words_encoded": stats["encoded"],
        "rows": len(rows),
        "skipped": {k: v for k, v in stats.items() if k != "encoded"},
        "bytes": out.stat().st_size,
    }
    print(json.dumps(report, ensure_ascii=False, indent=2))
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n",
                               encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
