#!/usr/bin/env python3
"""Import the 应物 input method into this repository as 足下.

应物音形足下输入法 and 应物输入法 are two products built from one text service.
The TSF layer, the candidate window, the language-bar indicator, the installer
and the build scripts are all scheme-agnostic: they open a librime session,
route keys and register with Windows. What differs is identity -- the scheme
id, the dictionary names, the install and user directories, the registry keys
and the CLSIDs.

This script makes that fork mechanically, so that the difference between the
two trees is exactly the token table below and nothing accidental:

    ../hengma-native/{src,installer,scripts}, CMakeLists.txt, VERSION,
        THIRD_PARTY_NOTICES.md
      ->  src/, installer/, scripts/, CMakeLists.txt, VERSION,
          THIRD_PARTY_NOTICES.md

Run it from anywhere:

    python tools/port_from_yingwu.py

It overwrites the ported files completely. Re-running it after editing them by
hand discards those edits, so treat the upstream tree as the source of truth
and put local differences in the EXTRA_PAIRS / DELETIONS tables here.

Two things are deliberately NOT ported:

* Icons. `src/ZuxiaTSF.ico` and `installer/setup/app.ico` are generated by
  `scripts/make-icon.ps1`, which renders a character. 应物 uses 应; a sibling
  that shares its icon is hard to tell apart in the Win+Space list, so 足下
  renders its own. Run:
      pwsh scripts/make-icon.ps1 -Char 足 -Out src/ZuxiaTSF.ico
      pwsh scripts/make-icon.ps1 -Char 足 -Out installer/setup/app.ico
* Build products: payload.cab/.ddf, payload_info.h, setup.u16.rc, *.res,
  *.exe and obj_*/ under installer/setup are generated by the build.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
UPSTREAM = REPO.parent / "hengma-native"

# ---------------------------------------------------------------------------
# Identity. Applied to file contents and to file names, in this order.
# ---------------------------------------------------------------------------
IDENTITY = [
    # Uppercase first: CMake cache variables and the COM-guard macros.
    ("HENGMA", "ZUXIA"),
    ("YINGWU", "ZUXIA"),
    ("Hengma", "Zuxia"),
    ("hengma", "zuxia"),
    ("Yingwu", "Zuxia"),
    ("yingwu", "zuxia"),
    ("衡码", "足下"),
    ("应物输入法", "应物音形足下输入法"),
    # Versions. 应物 ships 0.57-heng and carries two older strings in comments
    # and in the librime traits; 足下 tracks its scheme's 0.1.0.
    ("0.57-heng", "0.1.0"),
    ("0.57.0", "0.1.0"),
    ("0.3.1-alpha", "0.1.0"),
    ("0.3.0-alpha", "0.1.0"),
]

# The `hm` initialism stands for HengMa. The macro prefix, the namespace and
# the header name are all identity, so they go with it.
MECHANICAL = [
    ("hmcommon.h", "zxcommon.h"),
    ("HM_", "ZX_"),
    ("hm::", "zx::"),
    ("namespace hm {", "namespace zx {"),
    ("}  // namespace hm", "}  // namespace zx"),
]

# ---------------------------------------------------------------------------
# Blocks that must go before the token table runs.
#
# 应物's installer also removes a much older product ("衡码输入法", 0.3.0-alpha,
# %ProgramFiles%\Hengma) so that upgrading from it does not leave two text
# services registered. 应物 replaces that product; 足下 does not -- it is a
# sibling that must leave every other input method alone. With the setup
# replacements below, 足下 neither looks for nor deletes a neighbouring
# installation. This is why HM_LEGACY_* is deleted rather than renamed: a
# renamed legacy block would aim DeleteTree() at 应物's own directory.
# ---------------------------------------------------------------------------
LEGACY_DEFINES = """// 0.3.0-alpha shipped as "衡码输入法" under these names. The installer still
// recognises them so an upgrade unregisters and removes the old copy instead
// of leaving a second text service registered alongside the new one.
#define HM_LEGACY_DIRNAME     L"Hengma"
#define HM_LEGACY_TSF_DLL     L"HengmaTSF.dll"
#define HM_LEGACY_ARP_KEY     L"SOFTWARE\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Uninstall\\\\HengmaNative"
#define HM_LEGACY_PRODUCT_KEY L"SOFTWARE\\\\Hengma"

"""

LEGACY_FUNCTION = """// 0.3.0-alpha installed as 衡码输入法 under %ProgramFiles%\\Hengma with its own
// registry keys. Without this an upgrade would leave that copy registered, and
// the user would see two entries in the input-method list.
void RemoveLegacyInstall() {
  const std::wstring legacy = hm::ReadInstallRoot(HM_LEGACY_PRODUCT_KEY);
  if (!legacy.empty()) {
    const std::wstring x86 = legacy + L"\\\\x86\\\\" HM_LEGACY_TSF_DLL;
    const std::wstring x64 = legacy + L"\\\\x64\\\\" HM_LEGACY_TSF_DLL;
    if (hm::FileExists(x64)) hm::RegisterDll(hm::Regsvr32For64(), x64, true);
    if (hm::FileExists(x86)) hm::RegisterDll(hm::Regsvr32For32(), x86, true);
    hm::DeleteTree(legacy);
  }
  hm::RemoveKey(HM_LEGACY_ARP_KEY);
  hm::RemoveKey(HM_LEGACY_PRODUCT_KEY);
}

"""

DELETIONS = {
    "installer/setup/hmcommon.h": [LEGACY_DEFINES],
    "installer/setup/setup.cpp": [
        LEGACY_FUNCTION,
        # And its only caller.
        "  UnregisterAt(root);\n  RemoveLegacyInstall();\n",
    ],
}

# ---------------------------------------------------------------------------
# The one place where 足下 needs different behaviour rather than a different
# name. 衡码's structure code is a single fixed suffix, so a character has one
# complete code and the annotation is short by construction. 足下 accepts any
# two components in either order, so one character carries many equally
# complete codes -- 行 has nine, 应 six -- and printing them all would fill the
# candidate row.
# ---------------------------------------------------------------------------
ANNOTATE_OLD = """  std::wstring comment;
  for (const std::wstring& code : found->second) {
    if (!typed.empty() && code.rfind(typed, 0) != 0) continue;
    if (!comment.empty()) comment += L' ';
    comment += code;
  }
  if (comment.empty()) {
    // Nothing matched -- a fuzzy or mistyped code. Show every reading.
    for (const std::wstring& code : found->second) {
      if (!comment.empty()) comment += L' ';
      comment += code;
    }
  }
  candidate->comment = comment;
"""

ANNOTATE_NEW = """  // 足下 accepts any two components in either order, so one character can
  // carry many equally complete codes. Show the ones that continue what has
  // been typed and stop after four, leaving the row readable.
  constexpr size_t kMaxCodes = 4;
  std::wstring comment;
  size_t shown = 0;
  for (const std::wstring& code : found->second) {
    if (shown == kMaxCodes) {
      comment += L" \\u2026";
      break;
    }
    if (!typed.empty() && code.rfind(typed, 0) != 0) continue;
    if (!comment.empty()) comment += L' ';
    comment += code;
    ++shown;
  }
  if (shown == 0) {
    // Nothing matched -- a partial or mistyped code. Show the first readings.
    for (const std::wstring& code : found->second) {
      if (shown == kMaxCodes) {
        comment += L" \\u2026";
        break;
      }
      if (!comment.empty()) comment += L' ';
      comment += code;
      ++shown;
    }
  }
  candidate->comment = comment;
"""

# Per-file additions on top of the token table. Paths are the destination
# relative paths.
EXTRA_PAIRS = {
    "src/RimeEngine.cpp": [
        (ANNOTATE_OLD, ANNOTATE_NEW),
    ],
    # Fresh GUIDs. Both products register a keyboard TIP for the same language,
    # so a shared CLSID would make one silently replace the other: HKCR would
    # hold whichever registered last, and RemoveLanguageProfile during
    # registration would delete the sibling's Win+Space entry.
    "src/Globals.cpp": [
        ("0x57a9a4da,\n    0x60e5,\n    0x426d,\n"
         "    {0xa2, 0x20, 0x5c, 0x16, 0x2c, 0x97, 0x6c, 0xaa}",
         "0xa0073a11,\n    0xff52,\n    0x4185,\n"
         "    {0xa6, 0x55, 0xd0, 0xc9, 0x17, 0x1b, 0x78, 0x50}"),
        ("// {57A9A4DA-60E5-426D-A220-5C162C976CAA}",
         "// {A0073A11-FF52-4185-A655-D0C9171B7850}"),
        ("0xc22c0423,\n    0xc953,\n    0x4d85,\n"
         "    {0x8c, 0x80, 0xb4, 0x72, 0x51, 0x1a, 0x79, 0xe7}",
         "0x699b0ec1,\n    0x3fdb,\n    0x415d,\n"
         "    {0x89, 0xc0, 0x0e, 0x55, 0xaa, 0x2e, 0xff, 0xaf}"),
        ("// {C22C0423-C953-4D85-8C80-B472511A79E7}",
         "// {699B0EC1-3FDB-415D-89C0-0E55AA2EFFAF}"),
        ("0x35c3b3a4,\n    0xdc91,\n    0x41af,\n"
         "    {0x82, 0x9a, 0x36, 0x7f, 0x9e, 0x4b, 0x42, 0x0e}",
         "0x7b73df85,\n    0x7342,\n    0x4b2c,\n"
         "    {0x9a, 0x90, 0x41, 0x48, 0x25, 0x26, 0xb4, 0x7b}"),
        ("// {35C3B3A4-DC91-41AF-829A-367F9E4B420E}",
         "// {7B73DF85-7342-4B2C-9A90-41482526B47B}"),
    ],
    # The icon file name is legacy, not identity.
    "src/YingwuTSF.rc": [
        ('ICON "TextService.ico"', 'ICON "ZuxiaTSF.ico"'),
    ],
    # 足下 renders its own glyph: two products sharing the 应 icon would be
    # hard to tell apart in the input-method list.
    "scripts/make-icon.ps1": [
        ("# Renders the character 应 into a multi-resolution .ico.",
         "# Renders the character 足 into a multi-resolution .ico."),
        ("[string]$Char = '应',", "[string]$Char = '足',"),
    ],
    # 应物 ships a phrase dictionary; 足下 has none yet, so its two required
    # file lists must not ask for one -- every install would abort with
    # 「安装载荷不完整」. The candidate annotation table takes its place: it is
    # part of the shipped data set and its absence would silently cost the
    # candidate window its code annotations.
    "installer/setup/setup.cpp": [
        ('  const wchar_t* required[] = {L"\\\\data\\\\zuxia.schema.yaml",\n'
         '                               L"\\\\data\\\\zuxia.dict.yaml",\n'
         '                               L"\\\\data\\\\zuxia_phrases.dict.yaml",\n'
         '                               L"\\\\x86\\\\" ZX_TSF_DLL, '
         'L"\\\\x86\\\\rime.dll"};',
         '  const wchar_t* required[] = {L"\\\\data\\\\zuxia.schema.yaml",\n'
         '                               L"\\\\data\\\\zuxia.dict.yaml",\n'
         '                               L"\\\\data\\\\zuxia_char_codes.dict.yaml",\n'
         '                               L"\\\\x86\\\\" ZX_TSF_DLL, '
         'L"\\\\x86\\\\rime.dll"};'),
    ],
    "installer/Install-Yingwu.ps1": [
        ("    (Join-Path $SourceRoot 'data\\zuxia.dict.yaml'),\n"
         "    (Join-Path $SourceRoot 'data\\zuxia_phrases.dict.yaml')\n",
         "    (Join-Path $SourceRoot 'data\\zuxia.dict.yaml'),\n"
         "    (Join-Path $SourceRoot 'data\\zuxia_char_codes.dict.yaml')\n"),
    ],
    "THIRD_PARTY_NOTICES.md": [
        ("`src/TextService.ico` 与 `installer/setup/app.ico` 是「应」字的位图图标",
         "`src/ZuxiaTSF.ico` 与 `installer/setup/app.ico` 是「足」字的位图图标"),
    ],
    # docs/ is installed wholesale into the product. 待你定夺.md is a decision
    # log written for the maintainer, not user documentation.
    "CMakeLists.txt": [
        ('install(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/docs/" DESTINATION docs\n'
         '        FILES_MATCHING PATTERN "*.md")',
         '# 待你定夺.md is a decision log kept for the maintainer, not product\n'
         '# documentation, so it stays out of the installed tree.\n'
         'install(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/docs/" DESTINATION docs\n'
         '        FILES_MATCHING PATTERN "*.md" PATTERN "待你定夺.md" EXCLUDE)'),
    ],
}

# What to port. Explicit lists, because both trees contain generated files that
# must not be carried across.
TREES = [
    # The text service itself.
    ("src", "src", {".cpp", ".h", ".rc", ".def"}, set()),
    # The installer. Excluded: everything the build generates.
    ("installer", "installer", {".ps1", ".cmd", ".cpp", ".h", ".rc", ".bat",
                                 ".manifest"},
     {"payload.cab", "payload.ddf", "payload_info.h", "setup.u16.rc",
      "obj_setup", "obj_uninst"}),
    # Only the scripts that are not tied to 应物's data pipeline. rebuild-data
    # and run-tests drive generators and tests that do not exist here.
    ("scripts", "scripts", {".ps1"}, set()),
]

SCRIPT_INCLUDES = {"build.ps1", "fetch-librime.ps1", "make-icon.ps1"}

ROOT_FILES = ["CMakeLists.txt", "VERSION", "THIRD_PARTY_NOTICES.md"]

# A fork that still says Yingwu or hengma anywhere is a fork that will confuse
# the next person. Refuse to write one.
FORBIDDEN = ("Yingwu", "yingwu", "YINGWU", "hengma", "Hengma", "HENGMA",
             "衡码", "应物输入法", "hm::", "HM_", "hmcommon.h",
             "TextService.ico", "LEGACY", "legacy", "0.57", "0.3.0-alpha",
             "0.3.1-alpha",
             # 应物's CLSID, profile GUID and preserved-key GUID. Sharing any
             # of them would make the two products evict each other.
             "57a9a4da", "57A9A4DA", "c22c0423", "C22C0423",
             "35c3b3a4", "35C3B3A4")


def read(path: pathlib.Path):
    raw = path.read_bytes()
    bom = b""
    if raw.startswith(b"\xef\xbb\xbf"):
        bom = raw[:3]
        raw = raw[3:]
    return raw.decode("utf-8"), bom


def replace_all(text: str, pairs, where: str, changed: list, strict: bool) -> str:
    """Apply literal replacements.

    ``strict`` pairs must hit: they name something a file is expected to
    contain exactly one of, so a miss means upstream moved it and the port
    quietly stopped rebranding that spot.
    """
    for old, new in pairs:
        if old not in text:
            if strict:
                print(f"  MISS  {where}: {old[:60]!r}", file=sys.stderr)
            continue
        text = text.replace(old, new)
        changed.append(where)
    return text


def port_file(source: pathlib.Path, target: pathlib.Path, key: str,
              label: str, check: bool) -> int:
    """Port one file. ``key`` is its path upstream, ``label`` its path here."""
    text, bom = read(source)
    changed: list = []

    for block in DELETIONS.get(key, []):
        if block not in text:
            print(f"  MISS  {key}: block deletion", file=sys.stderr)
            continue
        text = text.replace(block, "")
        changed.append(key)

    text = replace_all(text, IDENTITY, key, changed, strict=False)
    text = replace_all(text, MECHANICAL, key, changed, strict=False)
    text = replace_all(text, EXTRA_PAIRS.get(key, []), key, changed, strict=True)

    leftovers = [token for token in FORBIDDEN if token in text]
    for token in leftovers:
        print(f"  LEFTOVER {label}: {token!r}", file=sys.stderr)

    if not check:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(bom + text.encode("utf-8"))
    print(f"port  {label}  ({len(changed)} changes)")
    return len(leftovers)


def walk(source_dir: pathlib.Path, suffixes: set, exclude: set):
    for path in sorted(source_dir.rglob("*")):
        if not path.is_file():
            continue
        if path.suffix.lower() not in suffixes:
            continue
        if any(part in exclude for part in path.relative_to(source_dir).parts):
            continue
        yield path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="report what would change, write nothing")
    args = parser.parse_args()

    if not UPSTREAM.is_dir():
        print(f"missing upstream tree: {UPSTREAM}", file=sys.stderr)
        return 1

    renamed = IDENTITY + MECHANICAL
    problems = 0
    count = 0

    for source_name, dest_name, suffixes, exclude in TREES:
        source_dir = UPSTREAM / source_name
        for path in walk(source_dir, suffixes, exclude):
            leaf = path.relative_to(source_dir).as_posix()
            if source_name == "scripts" and leaf not in SCRIPT_INCLUDES:
                continue
            # Keyed by the path upstream, so the tables above read as "the file
            # in 应物's tree", and every key is unique across the trees.
            key = f"{source_name}/{leaf}"
            relative = leaf
            for old, new in renamed:
                relative = relative.replace(old, new)
            problems += port_file(path, REPO / dest_name / relative, key,
                                  f"{dest_name}/{relative}", args.check)
            count += 1

    for name in ROOT_FILES:
        problems += port_file(UPSTREAM / name, REPO / name, name, name,
                              args.check)
        count += 1

    print(f"\n{count} files")
    if problems:
        print(f"{problems} leftover identity tokens -- fix the tables above",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
